 platform :ios, ‘8.0’

target 'Basic' do
  use_frameworks!


pod 'Basic', '~> 0.0.3'

  target 'BasicTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BasicUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
